# Generated by Django 5.2.4 on 2025-07-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeuser",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="Media/profile_pic"),
        ),
    ]
