# Generated by Django 5.2.4 on 2025-07-08 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_customeuser_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogerProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(max_length=200, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogersProfile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="viewersProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Bio", models.TextField(max_length=100, null=True)),
                ("interests", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "preferred_content_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("articles", "Articles"),
                            ("videos", "Videos"),
                            ("podcast", "both"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewersProfile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
